### ISSUE TITLE
Add babel-plugin-precompile-charcodes

### ISSUE THREAD

**Issue by fregante** [babel/minify#353]
I think [ben-eb/babel-plugin-precompile-charcodes](https://github.com/ben-eb/babel-plugin-precompile-charcodes) should be included in `babel-preset-babili`

### Input

```js
const at = '@'.charCodeAt(0);
```

### Output

```js
const at = 64;
```

**Comment by kangax** [comment]
Good idea! 

I just wonder why it only does this with `0` and not, say, `1` or any other number?

Also I just did a quick search on github and I see `charCodeAt()` used pretty often (which seems to act as if `0` was passed) so it'd be nice to include support for that as well.

/cc @ben-eb

**Comment by ben-eb** [comment]
@kangax That's mostly because I don't believe that people are going to write `"ab".charCodeAt(1)` - I guess they *might*, but I think it's easier to assume that instead of that, people would write `"b".charCodeAt(0)`. 😄 

Anyway at the time I was writing this for PostCSS (and related tokenizers) which use `str.charCodeAt(0)`: https://github.com/postcss/postcss/blob/cb5bb5e6a1015cd9d334e54000bc7a334f11ea77/lib/tokenize.es6#L1-L19
