### ISSUE TITLE
[duplicate] 'let' causing variables to disappear in for-loop

### ISSUE THREAD

**Issue by michaelmcleodnz** [babel/minify#485]
This only occurs in conjunction with the es2015 plugin.
The following code
```javascript
function getSum(data) {
  let total = 0;
  for (let i = 0; i < data.length; i++) {
    total += data[i];
  }
  return total;
}
```
gets transpiled to
```javascript
"use strict";function getSum(a){for(var c=0;c<a.length;c++)a[c];return b}
```
which returns the undefined variable `b`. Seemingly `total` has been removed.

The same code using `var i` instead of `let i` produces the expected result
```javascript
"use strict";function getSum(a){for(var c=0,b=0;b<a.length;b++)c+=a[b];return c}
```

**Comment by hzoo** [comment]
Hey @michaelmcleodnz! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by michaelmcleodnz** [comment]
If it helps, this seems to be because `var`s declared before a for-loop are pulled inside the for-loop declaration, which can't be done with `let`s because it changes their scope.
Babili knows not to pull the `let`s inside a for-loop without the es2015 plugin, so I'm not sure what the order of operations would be here that causes it to pull the variable inside the for-loop and then decide that it can be optimised away because it is `let`-scoped.

**Comment by michaelmcleodnz** [comment]
I've found that this issue has already been reported in #430 and #412.
[Line 89 of merge-sibling-variables](../blob/b014c3f46aaec5446f914599140c8f259ac35267/packages/babel-plugin-transform-merge-sibling-variables/src/index.js#L89) checks that the for-loop declaration is of type `var`, but presumably somewhere in [minify-dead-code-elimination](../blob/b014c3f46aaec5446f914599140c8f259ac35267/packages/babel-plugin-minify-dead-code-elimination/src/index.js) it is still believed to be of type `let`.

**Comment by boopathi** [comment]
Fixed in #713

**Comment by armujahid** [comment]
This issue is occurring again on latest version of `babel-preset-minify`. For and while loops are eating cont/let declarations immediately before them

[Demo of issue](https://babeljs.io/en/repl#?babili=true&browsers=IE%2011&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABMOcAUBKRBvAUIgxCBAZykSgFMzEBeRARgG59CB3ACxgBtLE0GWPAEhhAIwBOlAIYBrFoUQBfVgSlQQEpFTIKVuXKEiwEiAOaUoAZRABbNABNpUaUNa9yUOC-51EABgVkOAl-D0QYP0CIxAAeRCcXADpeMDMoDiYIgGpst0UvH0Rs-kTpAG0YAF0glTVLTW1vaW4WfSNoeCQxaQlMHHdLRGkxCD8AcgYAJgBmcdYUULRwyPpoyPjyhgAaKe2ZqpTKNIysmFz8xWHRvxGx7MRxmYAWAFZx4VY6olI4XhS4GY0HcMLh9EA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=babili%2Cenv&prettier=true&targets=&version=6.26.0&envVersion=1.6.2)


Should I open new issue or should this issue be reopened?

**Comment by armujahid** [comment]
As a workaround, I am now using below configs

```
// Below configs are copied from https://github.com/Polymer/tools/blob/master/packages/build/src/js-transform.ts
// Disable the minify-constant-folding plugin because it has a bug relating
// to invalid substitution of constant values into export specifiers:
// https://github.com/babel/minify/issues/820
evaluate: false,

// TODO(aomarks) Find out why we disabled this plugin.
simplifyComparisons: false,

// Prevent removal of things that babel thinks are unreachable, but sometimes
// gets wrong: https://github.com/Polymer/tools/issues/724
deadcode: false,

// Disable the simplify plugin because it can eat some statements preceeding
// loops. https://github.com/babel/minify/issues/824
simplify: false,

// This is breaking ES6 output. https://github.com/Polymer/tools/issues/261
mangle: false,
```
