### ISSUE TITLE
babel-plugin-transform-inline-environment-variables - Blacklist/whitelist?

### ISSUE THREAD

**Issue by jupl** [babel/minify#513]
I've been using `babel-plugin-node-env-inline` for a while when compiling code that is to be used in Node. I'm getting to the point where I would like to inline other environment variables for dead code elimination while not inlining others for use with `dotenv`. Would it make sense to have an optional blacklist/whitelist to specify which environment variables should be inlined or not?

**Comment by boopathi** [comment]
For code that is run in Node, is inlining environment variables a common use case at all ?

**Comment by jupl** [comment]
Like I said, I would like to inline some environment variables besides `NODE_ENV` for DCE while not inlining others for use with `dotenv` when using the Babili CLI.

**Comment by boopathi** [comment]
DCE for nodejs code looks like a specific use case and one can write a babel-plugin to do that and it doesn't have to be in babili. Closing this for now. Will reopen if it's a common requirement.

**Comment by JakeDluhy** [comment]
I actually have a use case for this that might warrant this change. We currently have an app that builds a web application using `webpack` and an electron application using `electron-forge` (we don't use webpack so that we don't have to deal with native module workarounds).

However when building for webpack we use the `Webpack.DefinePlugin` to make our environment variable substitutions which obviously won't work with `electron-forge`. So we precompile with `babel`, using the `transform-inline-environment-variables` plugin to make our env variable swaps.

Unfortunately, we also are creating our app so that when we distribute it on tablets, it reads one env variable off the system `process.env.SUBDOMAIN` (we control tablet management, and we don't want to build specifically for each tablet). And our problem is that `process.env.SUBDOMAIN` gets set to `undefined` with the plugin. It would be nice if we could whitelist specific env variables to transform.

**Comment by boopathi** [comment]
> Let me know if you'd like me to submit a PR

sure 👍

**Comment by JakeDluhy** [comment]
I've had a PR open for this for almost two months now. I'm waiting for reviewer feedback that hasn't been coming. I'd really like to get this merged. Is there anything I can do to help speed up the process?
