### ISSUE TITLE
Variables' types are inffered inaccuratly

### ISSUE THREAD

**Issue by RogerKang** [babel/minify#636]
babili transfer `===` to `==` which is not expected because the types of variables are not same. 

#### Input Code
```js
var a = false;
a=0;   // change the type after it is initiated
if (false === a) {
  throw new Error('Should not equal');
} else {
  console.log('Good');
}
```

#### Actual Output
```js
var b=!1;if(b=0,!1==b)throw new Error('Should not equal');else console.log('Good');
```

#### Expected Output
```js
var b=!1;if(b=0,!1===b)throw new Error('Should not equal');else console.log('Good');
```

Seems that babili infers variables' types only based on their initiation.

**Comment by fishbar** [comment]
`babel-plugin-transform-simplify-comparison-operators` did it

**Comment by boopathi** [comment]
you can set `simplifyComparisons: false` in your babel-minify options. [This is how we compare types in babel - and it isn't perfect](https://github.com/babel/babel/blob/830c527bb7873b29f671a3568b21b4a6af98ceda/packages/babel-traverse/src/path/inference/index.js#L105-L112). If this issue comes up frequently, we'll disable the plugin by default. I'll close this issue for now.
