### ISSUE TITLE
Incorrect minification within try block and destructuring

### ISSUE THREAD

**Issue by nachoab** [babel/minify#871]
This function is incorrectly minified.  It happens when using 2 variables and not using one:

```js
async function example() {
  var foo, bar;
  try {
    [foo, bar] = await Promise.all([req(1), req(2)]);
  } catch(e) {}
  console.log(foo);
}
```

**Actual Output**
foo and bar and ignored, so the output is broken

```js
async function example() {
  var a;
  try {
    await Promise.all([req(1), req(2)]);
  } catch (c) {}
  console.log(a);
}
```

See it here:

https://babeljs.io/repl/#?babili=true&browsers=&build=&builtIns=false&code_lz=IYZwngdgxgBAZgV2gFwJYHsIwKYA9gC2ADgDbYAUAlDAN4BQMMAbsAE7zroA0MARmwG4GMZKzC1hjANpxOPfqwC6MALwxgAd2CpkMAAqt0BVCGwA6YCRLkprbAEdyARko87jgEyVFlIYwC-MFDAyFAAFuTY1DT-wlCYIOhkZiToAObksui-dP5AA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=false&presets=babili&prettier=true&targets=&version=6.26.0&envVersion=

**Comment by Cyp** [comment]
I can reproduce this with latest babel-minify.

With all passes on (but babel-preset-env off, since that results in a long mess of code) —
```js
async function example(){var a;try{await Promise.all([req(1),req(2)])}catch(a){}console.log(a)}
```

Disabling the `deadcode` pass gives something that looks correct:
```js
async function example(){var a,b;try{[a,b]=await Promise.all([req(1),req(2)])}catch(a){}console.log(a)}
```

Removing the `try{` and `}catch(c){}`, with all passes on gives something that also looks correct:
```js
async function example(){var a,b;[a,b]=await Promise.all([req(1),req(2)]),console.log(a)}
```

If disabling the `simplify` pass on the version without try/catch, `deadcode` then breaks it again:
```js
async function example(){var a;await Promise.all([req(1),req(2)]);console.log(a)}
```

It seems that `simplify` changing `;` to `,` stops `deadcode` from breaking the code in some cases, but that can't happen with the try/catch.
